### ISSUE TITLE
Assertion error with Jemalloc: 'assertion failed: layout.size() != 0'

### ISSUE THREAD

**Issue by yossyX** [denoland/deno_core#170]
Hello,

I'm encountering an assertion error when using the deno_core crate in conjunction with jemalloc. I've detailed the setup and error reproduction steps below.

**Cargo.toml:**

```toml
[package]
name = "deno_core-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
deno_core = "0.204.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
```

**main.rs:**

```rust
#[cfg(not(target_env = "msvc"))]
use tikv_jemallocator::Jemalloc;

#[cfg(not(target_env = "msvc"))]
#[global_allocator]
static GLOBAL: Jemalloc = Jemalloc;

#[tokio::main]
async fn main() {
    let mut js_runtime = deno_core::JsRuntime::new(deno_core::RuntimeOptions::default());
    if let Err(e) = js_runtime.execute_script_static("", "var a = {test:1;") {
        eprintln!("{}", e);
    }
}
```

**Error with RUST_BACKTRACE=1:**

```
thread 'main' panicked at 'assertion failed: layout.size() != 0', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tikv-jemallocator-0.5.4/src/lib.rs:102:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:117:5
   3: <tikv_jemallocator::Jemalloc as core::alloc::global::GlobalAlloc>::alloc
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tikv-jemallocator-0.5.4/src/lib.rs:102:9
   4: __rust_alloc
             at ./src/main.rs:6:16
   5: alloc::alloc::alloc
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/alloc.rs:102:9
   6: v8::string::<impl v8::data::String>::to_rust_string_lossy
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.74.3/src/string.rs:565:20
   7: deno_core::error::JsStackFrame::from_v8_message
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.204.0/error.rs:210:13
   8: deno_core::error::JsError::inner_from_v8_exception
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.204.0/error.rs:414:36
   9: deno_core::error::JsError::from_v8_exception
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.204.0/error.rs:265:5
  10: deno_core::error::exception_to_err_result
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.204.0/error.rs:705:22
  11: deno_core::runtime::jsrealm::JsRealm::execute_script
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.204.0/runtime/jsrealm.rs:390:16
  12: deno_core::runtime::jsruntime::JsRuntime::execute_script_static
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.204.0/runtime/jsruntime.rs:1196:5
  13: deno_core_test::main::{{closure}}
             at ./src/main.rs:11:5
  14: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  15: tokio::runtime::coop::with_budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  16: tokio::runtime::coop::budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  17: tokio::runtime::park::CachedParkThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  18: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  19: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  20: tokio::runtime::context::runtime::enter_runtime
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  21: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  22: tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  23: deno_core_test::main
             at ./src/main.rs:11:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
```

I've deliberately introduced a syntax error in the sample JavaScript code. It seems that when such an error is present, an attempt is made to allocate memory of size 0 in `to_rust_string_lossy`.

I'm unsure if this is a compatibility issue between `deno_core` and `jemalloc`, or if I've missed something in the configuration. Any assistance on this would be greatly appreciated. Thank you.

**Comment by bartlomieju** [comment]
CC @mmastrac

**Comment by yossyX** [comment]
@bartlomieju @mmastrac
Thank you so much for the quick fix!
