### ISSUE TITLE
Console.log works for simple types, but returns "TypeError: TypedArrayPrototypeSymbolToStringTag at #stringify (ext:core/01_core.js:365:18) is not a function" when calling console.log with Struct argument in embedded Deno runtime

### ISSUE THREAD

**Issue by kairoswater-jason** [denoland/deno_core#571]
I have an application that embeds deno and the deno_console extension.

With my sample program simple invocations of `console.log` work flawlessly for most types.

But when attempting to log a parameter passed from my program into the following function `export function decodeUplink(input) { console.log("decodeUplink", input); ... }` I encounter a runtime error:

```
2024-02-12T10:17:39.747-05:00	thread 'main' panicked at src/javascript.rs:156:59:
2024-02-12T10:17:39.747-05:00	called `Result::unwrap()` on an `Err` value: TypeError: TypedArrayPrototypeSymbolToStringTag is not a function
2024-02-12T10:17:39.747-05:00	at #stringify (ext:core/01_core.js:365:18)
2024-02-12T10:17:39.747-05:00	at Array.map (<anonymous>)
2024-02-12T10:17:39.747-05:00	at CoreConsole.log (ext:core/01_core.js:374:36)
2024-02-12T10:17:39.747-05:00	at decodeUplink (ext:codec.js:79:13)
2024-02-12T10:17:39.747-05:00	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```

Here are some minimal details for reproduction

cargo dependencies
```
deno_core = { version = "0.260.0", default-features = false }
deno_console = "0.137.0" # requires 0.260 above
```

argument passed to decodeUplink and into console.log is a structure of type:

```
#[derive(Serialize)]
pub struct UplinkDecodingParameters {
    #[serde(rename = "fPort")]
    f_port: u8,
    bytes: Vec<u8>,
}

```

snippet of building the runtime, adding extensions, and executing decodeUplink
```
#[derive(Debug, Default)]
pub struct CodecFunctionReferences {
    pub decode_uplink: Option<v8::Global<v8::Function>>,
    pub encode_downlink: Option<v8::Global<v8::Function>>,
    pub decode_downlink: Option<v8::Global<v8::Function>>,
}

#[op2]
pub fn op_register_codec(#[state] codec : &mut CodecFunctionReferences, #[global] dec_up : v8::Global<v8::Function>
                         , #[global] enc_down : v8::Global<v8::Function>, #[global] dec_down : v8::Global<v8::Function>) {
    println!("Register codec");
    codec.decode_uplink.replace(dec_up);
    codec.encode_downlink.replace(enc_down);
    codec.decode_downlink.replace(dec_down);
}

//Load a fresh V8 interpreter with all relevant modules and extensions.
//Return the interpreter read to have one of the codec functions called.
pub async fn prepare_runtime() -> JsRuntime {
    const JS_CODEC: &'static [ExtensionFileSource] =
        &[ExtensionFileSource::new("ext:codec.js", CODEC)];

    let ext_codec = Extension {
        name: "ext_codec",
        ops: Borrowed(&[op_register_codec::DECL]),
        op_state_fn: Some(Box::new(|state| {
            state.put(CodecFunctionReferences::default());
        })),
        esm_files: Borrowed(JS_CODEC),
        esm_entry_point: Some("ext:codec.js"),
        ..Default::default()
    };

    let mut ext_console = deno_console::deno_console::init_ops_and_esm();
    ext_console.esm_entry_point=Some("ext:deno_console/01_console.js");

    // Initialize a runtime instance
    let mut runtime = JsRuntime::new(RuntimeOptions {
        extensions: vec![ext_codec, ext_console],
        ..Default::default()
    });

    const JS_MAIN : ModuleCodeString = ModuleCodeString::Static("import {Console} from 'ext:deno_console/01_console.js';import { decodeUplink, encodeDownlink, decodeDownlink } from 'ext:codec.js'; let console = new Console(Deno.core.print); Deno.core.ops.op_register_codec(decodeUplink, encodeDownlink, decodeDownlink);");


    let main_module = resolve_url("ext:main.js").unwrap();
    let mod_id = runtime.load_main_module(&main_module, Some(JS_MAIN)).await.unwrap();
    let result = runtime.mod_evaluate(mod_id);
    runtime.run_event_loop(PollEventLoopOptions::default()).await.unwrap();
    result.await.unwrap();

    return runtime;
}

pub async fn test(mut runtime: JsRuntime, f_port : u8, bytes : Vec<u8>) -> DecodedUplink {
    let param = UplinkDecodingParameters {
        f_port,
        bytes,
    };

    let arg = {
        let mut scope = runtime.handle_scope();
        let val=serde_v8::to_v8(&mut scope, param).unwrap();
        v8::Global::new(&mut scope, val)
    };

    let func = {
        let codec: CodecFunctionReferences = runtime.op_state().borrow_mut().take();
        codec.decode_uplink.unwrap().clone()
    };

    let val = runtime.call_with_args(&func, &[arg]).await.unwrap();

    let mut scope = runtime.handle_scope();
    let local=val.to_v8(&mut scope);
    let deserialized: serde_v8::Result<DecodedUplink> =serde_v8::from_v8(&mut scope, local);
    println!("{:?}", deserialized);

    deserialized.unwrap()
}
```

notably, my "main" module is the following
```
import {Console} from 'ext:deno_console/01_console.js';
import { decodeUplink, encodeDownlink, decodeDownlink } from 'ext:codec.js';
let console = new Console(Deno.core.print);
Deno.core.ops.op_register_codec(decodeUplink, encodeDownlink, decodeDownlink);
```

Is it possible that my main module is somehow violating an assumption made by `deno_console`?

It seems that `01_core.js` is automatically included and setup by the runtime. And that `01_console.js` imports from `core` and etc.

It's not clear to me how I could have caused `console.log` to fail to find the built-in core functions (which seem to be automatically included from the BUILTIN_SOURCES constant at [jsruntime.rs:282](https://github.com/denoland/deno_core/blob/5beb975e20a6f01cc84e927139f778e525f7fd8c/core/runtime/jsruntime.rs#L282) )

**Comment by bartlomieju** [comment]
Your code is fine, it's a bug in deno_core: https://github.com/denoland/deno_core/issues/546.

@mmastrac coukd you remove that code path for the time being?

**Comment by mmastrac** [comment]
Fixed in https://github.com/denoland/deno_core/pull/572
